# Site
name: 'The Intrapreneur'
description: 'Disrupt organizations from the inside out.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
email: 'editor@theintrapreneur.co'

# E-mail subscription service
# mailchimp-list: 'https://theintrapreneur.us9.list-manage.com/subscribe/post?u=76280b57efb725c7994bbb584&amp;id=965f8f18c1'
mailerlite-list: 'https://assets.mailerlite.com/jsonp/248919/forms/73798747909260573/subscribe'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

authors:
    editor:
      name: The Editor
      site: https://theintrapreneur.co
      avatar: assets/images/avatar.png
      about: A futurist discovering the present.
      bio: Lucas is a technologist and has been leading the research, discovery, and creation of new technologies and products in R&D for big techs, and running startups.
      email: contact@theintrapreneur.co
      twitter: https://twitter.com/lucasboscaini
      linkedin: https://www.linkedin.com/in/lucasboscaini/

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: editor

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [LICENSE, README.md, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules, bkp]
